stages:
  - play GitTerra

GitTerra:
  stage: play GitTerra
  image: node:latest
  needs: []
  script:
    - echo "Let's play GitTerra!"
    # - set
    # - find . -not -path './.git' -not -path './.git/*'
    - mkdir -p /tmp/gitterra/scc
    - git clone --single-branch -b timelapse https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/gitterra/GitTerra.git /tmp/gitterra/gitterra
    - (cd /tmp/gitterra/gitterra && npm install)
    - wget https://github.com/boyter/scc/releases/download/v3.2.0/scc_Linux_x86_64.tar.gz -O /tmp/gitterra/scc/scc.gz
    - tar -C /tmp/gitterra/scc -xvf /tmp/gitterra/scc/scc.gz
    - chmod +x /tmp/gitterra/scc/scc
    - echo "Fetching history from ${CI_PAGES_URL}/history.json"
    - curl -f -o history.json ${CI_PAGES_URL}/history.json
    - node /tmp/gitterra/gitterra/src/generateMap.js ./ /tmp/gitterra/scc/scc
  artifacts:
    paths:
      - index.html
      - history.json
